# [Prof. Otávio Parraga](mailto:otavio.parraga@pucrs.br)

## Programação Orientada a Dados (POD) - Turma 11 (POD_98H04-06) 2025/1

**Descrição**: Trabalho Individual: Programação Funcional

**Copyright &copy;**: Este documento está sob a licensa da Criative Commons [BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode)

**Dataset**: [Pokemon](https://gist.github.com/armgilles/194bcff35001e7eb53a2a8b441e8b2c6)

Definição resumida sobre funções do paradigma funcional: são funções que são puras, que não apresentam efeito colateral, podem ser de alta ordem, podem ser currificadas e não utilizam laços de repetição.

Atenção: Explicar como funcionam todas as funções criadas através de comentário do Python (`#`). Você também será avaliado por esta explicação. 

### Trabalho realizado por:

*Pedro Henrique Fernandes Tomielo*

# Parte 1: Dataset Pokemon

### Recursos auxiliares
Abaixo você encontra as **Únicas bibliotecas permitidas** para este trabalho:

```python
import csv
import functools
import itertools
import operator
```

Além das bibliotecas permitidas, abaixo ainda estão as funções auxiliares que você pode utilizar para testar suas implementações. Elas não são do paradigma funcional, mas são necessárias para a avaliação.

In [36]:
import csv
from functools import reduce
from itertools import groupby
# from operator import *

def mostra_dados(nome_arq, f, *args):
    """
    Função auxiliar para mostrar o resultado da execução de uma função do paradigma funcional.
    A função abre um arquivo CSV e passa para função do paradigma funcional um objeto DictReader e 
    depois mostra o resultado na tela.
    """
    with open(nome_arq, "r", encoding='utf-8-sig') as arq:
        dados = csv.DictReader(arq, delimiter=',')
        fdados = f(dados, *args)
        try:
            iterator = iter(fdados)
        except TypeError:
            print(fdados)
        else:
            for linha in fdados:
                print(linha)
                
def salvar_dados(nome_arq, new_file, f):
    """
    Função auxiliar que chama uma função do paradigma funcional e depois salva o resultado em um arquivo CSV!
    A função abre um arquivo CSV e passa para função do paradigma funcional um objeto DictReader e 
    depois salva a saída em um arquivo CSV
    """
    with open(nome_arq, "r", encoding='utf-8-sig') as arq:
        dados=csv.DictReader(arq, delimiter=',')
        fdados = list(f(dados))
        fieldnames = fdados[0].keys()
        
    with open(new_file, "w", encoding='utf-8-sig') as arq:
        try:
            iterator=iter(fdados)
        except TypeError:
            return False
        else:
            writer = csv.DictWriter(arq, fieldnames=fieldnames)
            writer.writeheader()
            for i in fdados:
                writer.writerow(i)

In [37]:
mostra_dados('pokemon.csv', lambda x: x)

{'#': '1', 'Name': 'Bulbasaur', 'Type 1': 'Grass', 'Type 2': 'Poison', 'Total': '318', 'HP': '45', 'Attack': '49', 'Defense': '49', 'Sp. Atk': '65', 'Sp. Def': '65', 'Speed': '45', 'Generation': '1', 'Legendary': 'False'}
{'#': '2', 'Name': 'Ivysaur', 'Type 1': 'Grass', 'Type 2': 'Poison', 'Total': '405', 'HP': '60', 'Attack': '62', 'Defense': '63', 'Sp. Atk': '80', 'Sp. Def': '80', 'Speed': '60', 'Generation': '1', 'Legendary': 'False'}
{'#': '3', 'Name': 'Venusaur', 'Type 1': 'Grass', 'Type 2': 'Poison', 'Total': '525', 'HP': '80', 'Attack': '82', 'Defense': '83', 'Sp. Atk': '100', 'Sp. Def': '100', 'Speed': '80', 'Generation': '1', 'Legendary': 'False'}
{'#': '3', 'Name': 'VenusaurMega Venusaur', 'Type 1': 'Grass', 'Type 2': 'Poison', 'Total': '625', 'HP': '80', 'Attack': '100', 'Defense': '123', 'Sp. Atk': '122', 'Sp. Def': '120', 'Speed': '80', 'Generation': '1', 'Legendary': 'False'}
{'#': '4', 'Name': 'Charmander', 'Type 1': 'Fire', 'Type 2': '', 'Total': '309', 'HP': '39', 'Att

In [43]:
with open('pokemon.csv', 'r', encoding='utf-8-sig') as arq:
    dados = csv.DictReader(arq, delimiter=',')
    pokemons = list(dados) 
# Exemplos de uso:
pokemons

## 1. Limpe o conjunto de dados aplicando as seguintes regras:
1. Para os pokémons que não possuem o segundo `Type 2`, coloque o mesmo valor do `Type 1` no `Type 2`.
2. Transforme os nomes dos pokémons para letras minúsculas.
3. Adicionar uma coluna nova `TipoDefinitivo` composta pela concatenação dos dois tipos de cada pokemon
   (por exemplo, se o `Type 1` for "Fire" e o `Type 2` for "Flying", o `TipoDefinitivo` será "Fire-eFlying").
4. Salve o conjunto de dados limpo em um arquivo chamado `pokemon_clean.csv`.

### Exemplo de saída no novo csv:
```python
{'#': '1', 'Name': 'bulbasaur', 'Type 1': 'Grass', 'Type 2': 'Poison', 'Total': '318', 'HP': '45', 'Attack': '49', 'Defense': '49', 'Sp. Atk': '65', 'Sp. Def': '65', 'Speed': '45', 'Generation': '1', 'Legendary': 'False', 'TipoDefinitivo': 'Grass-Poison'}
{'#': '2', 'Name': 'ivysaur', 'Type 1': 'Grass', 'Type 2': 'Poison', 'Total': '405', 'HP': '60', 'Attack': '62', 'Defense': '63', 'Sp. Atk': '80', 'Sp. Def': '80', 'Speed': '60', 'Generation': '1', 'Legendary': 'False', 'TipoDefinitivo': 'Grass-Poison'}
{'#': '3', 'Name': 'venusaur', 'Type 1': 'Grass', 'Type 2': 'Poison', 'Total': '525', 'HP': '80', 'Attack': '82', 'Defense': '83', 'Sp. Atk': '100', 'Sp. Def': '100', 'Speed': '80', 'Generation': '1', 'Legendary': 'False', 'TipoDefinitivo': 'Grass-Poison'}
{'#': '3', 'Name': 'venusaurmega venusaur', 'Type 1': 'Grass', 'Type 2': 'Poison', 'Total': '625', 'HP': '80', 'Attack': '100', 'Defense': '123', 'Sp. Atk': '122', 'Sp. Def': '120', 'Speed': '80', 'Generation': '1', 'Legendary': 'False', 'TipoDefinitivo': 'Grass-Poison'}
{'#': '4', 'Name': 'charmander', 'Type 1': 'Fire', 'Type 2': 'Fire', 'Total': '309', 'HP': '39', 'Attack': '52', 'Defense': '43', 'Sp. Atk': '60', 'Sp. Def': '50', 'Speed': '65', 'Generation': '1', 'Legendary': 'False', 'TipoDefinitivo': 'Fire-Fire'}
{'#': '5', 'Name': 'charmeleon', 'Type 1': 'Fire', 'Type 2': 'Fire', 'Total': '405', 'HP': '58', 'Attack': '64', 'Defense': '58', 'Sp. Atk': '80', 'Sp. Def': '65', 'Speed': '80', 'Generation': '1', 'Legendary': 'False', 'TipoDefinitivo': 'Fire-Fire'}
...
```


In [110]:
def padronizar_tipos(lista: list[dict]) -> list[dict]:
    # Define uma função lambda (função anônima) que ajusta o campo 'Type 2' de cada Pokémon
    ajusta_type2 = lambda item: {
        **item,  # Mantém todos os campos do dicionário original
        'Type 2': item['Type 2']  # Se 'Type 2' já estiver preenchido (não é None nem string vazia), mantém
        if item.get('Type 2') not in (None, '')  # Verifica se 'Type 2' está vazio
        else item['Type 1']  # Caso esteja vazio, copia o valor de 'Type 1' para 'Type 2'
    }

    # Aplica a função ajusta_type2 a todos os elementos da lista usando map e retorna como uma nova lista
    return list(map(ajusta_type2, lista))


In [40]:
def transformar_nome_para_minusculo(lista: list[dict]) -> list[dict]:
    # Aplica uma transformação em cada item da lista usando map
    return list(
        map(
            # Para cada item (dicionário), cria uma cópia com todos os campos iguais,
            # exceto o campo 'Name', que é convertido para letras minúsculas
            lambda item: {
                **item,                      # copia todos os campos do dicionário original
                'Name': item['Name'].lower()  # transforma o valor de 'Name' em minúsculo
            },
            lista  # lista original de dicionários
        )
    )


In [41]:
def criar_tipo_definitivo(lista: list[dict]) -> list[dict]:
    # Define uma função lambda que cria um novo campo 'TipoDefinitivo' para cada item da lista
    tipo_definitivo = lambda item: {
        **item,  # copia todos os campos do dicionário original
        'TipoDefinitivo': item['Type 1'] + '-e' + item['Type 2']  # concatena os tipos com '-e' se forem diferentes
        if item['Type 1'] != item['Type 2']
        else item['Type 1'] + '-' + item['Type 2']  # se forem iguais, concatena com apenas '-'
    }

    # Aplica a função a todos os itens da lista e retorna como nova lista
    return list(map(tipo_definitivo, lista))


In [145]:
def pipeline(iterabe):
    # Aplica a função padronizar_tipos primeiro:
    # Preenche 'Type 2' com o valor de 'Type 1' caso esteja vazio
    return criar_tipo_definitivo(
        # Em seguida, transforma todos os nomes de Pokémon para letras minúsculas
        transformar_nome_para_minusculo(
            # Primeiro passo: padroniza os tipos
            padronizar_tipos(iterabe)
        )
    )


In [146]:
salvar_dados('pokemon.csv', 'pokemons_tratado.csv', pipeline)

In [147]:
mostra_dados('pokemons_tratado.csv', lambda x: x)

{'#': '1', 'Name': 'bulbasaur', 'Type 1': 'Grass', 'Type 2': 'Poison', 'Total': '318', 'HP': '45', 'Attack': '49', 'Defense': '49', 'Sp. Atk': '65', 'Sp. Def': '65', 'Speed': '45', 'Generation': '1', 'Legendary': 'False', 'TipoDefinitivo': 'Grass-ePoison'}
{'#': '2', 'Name': 'ivysaur', 'Type 1': 'Grass', 'Type 2': 'Poison', 'Total': '405', 'HP': '60', 'Attack': '62', 'Defense': '63', 'Sp. Atk': '80', 'Sp. Def': '80', 'Speed': '60', 'Generation': '1', 'Legendary': 'False', 'TipoDefinitivo': 'Grass-ePoison'}
{'#': '3', 'Name': 'venusaur', 'Type 1': 'Grass', 'Type 2': 'Poison', 'Total': '525', 'HP': '80', 'Attack': '82', 'Defense': '83', 'Sp. Atk': '100', 'Sp. Def': '100', 'Speed': '80', 'Generation': '1', 'Legendary': 'False', 'TipoDefinitivo': 'Grass-ePoison'}
{'#': '3', 'Name': 'venusaurmega venusaur', 'Type 1': 'Grass', 'Type 2': 'Poison', 'Total': '625', 'HP': '80', 'Attack': '100', 'Defense': '123', 'Sp. Atk': '122', 'Sp. Def': '120', 'Speed': '80', 'Generation': '1', 'Legendary': '

## 2. Contabilize quntos pokémons existem por geração

### Exemplo de saída:
```python
('1', 166)
('2', 106)
('3', 160)
('4', 121)
('5', 165)
('6', 82)
```

In [148]:
def contabilizar_pokemons_geracao(iterable):
    # Ordena os Pokémon pela geração (necessário para o groupby funcionar corretamente)
    iterable_sorted = sorted(iterable, key=lambda x: int(x['Generation']))

    # Agrupa os Pokémon por geração (o resultado é um iterador de pares: (geração, grupo_de_pokemons))
    itareble_grouped = groupby(iterable_sorted, lambda x: x['Generation'])

    # Para cada grupo, retorna uma tupla (geração, quantidade de pokémons nesse grupo)
    # Converte o iterador x[1] em lista para poder contar os elementos com len()
    return list(map(lambda x: (x[0], len(list(x[1]))), itareble_grouped))


In [149]:
mostra_dados('pokemons_tratado.csv', contabilizar_pokemons_geracao)

('1', 166)
('2', 106)
('3', 160)
('4', 121)
('5', 165)
('6', 82)


## 3. Aponte qual o pokémon com maior valor de `Speed` para cada `TipoDefinitivo`

### Exemplo de saída:
```python
('Bug-Bug', {'#': '617', 'Name': 'accelgor', 'Type 1': 'Bug', 'Type 2': 'Bug', 'Total': '495', 'HP': '80', 'Attack': '70', 'Defense': '40', 'Sp. Atk': '100', 'Sp. Def': '60', 'Speed': '145', 'Generation': '5', 'Legendary': 'False', 'TipoDefinitivo': 'Bug-Bug'})
('Bug-Electric', {'#': '596', 'Name': 'galvantula', 'Type 1': 'Bug', 'Type 2': 'Electric', 'Total': '472', 'HP': '70', 'Attack': '77', 'Defense': '60', 'Sp. Atk': '97', 'Sp. Def': '60', 'Speed': '108', 'Generation': '5', 'Legendary': 'False', 'TipoDefinitivo': 'Bug-Electric'})
('Bug-Fighting', {'#': '214', 'Name': 'heracross', 'Type 1': 'Bug', 'Type 2': 'Fighting', 'Total': '500', 'HP': '80', 'Attack': '125', 'Defense': '75', 'Sp. Atk': '40', 'Sp. Def': '95', 'Speed': '85', 'Generation': '2', 'Legendary': 'False', 'TipoDefinitivo': 'Bug-Fighting'})
('Bug-Fire', {'#': '637', 'Name': 'volcarona', 'Type 1': 'Bug', 'Type 2': 'Fire', 'Total': '550', 'HP': '85', 'Attack': '60', 'Defense': '65', 'Sp. Atk': '135', 'Sp. Def': '105', 'Speed': '100', 'Generation': '5', 'Legendary': 'False', 'TipoDefinitivo': 'Bug-Fire'})
('Bug-Flying', {'#': '291', 'Name': 'ninjask', 'Type 1': 'Bug', 'Type 2': 'Flying', 'Total': '456', 'HP': '61', 'Attack': '90', 'Defense': '45', 'Sp. Atk': '50', 'Sp. Def': '50', 'Speed': '160', 'Generation': '3', 'Legendary': 'False', 'TipoDefinitivo': 'Bug-Flying'})
('Bug-Ghost', {'#': '292', 'Name': 'shedinja', 'Type 1': 'Bug', 'Type 2': 'Ghost', 'Total': '236', 'HP': '1', 'Attack': '90', 'Defense': '45', 'Sp. Atk': '30', 'Sp. Def': '30', 'Speed': '40', 'Generation': '3', 'Legendary': 'False', 'TipoDefinitivo': 'Bug-Ghost'})
```

In [150]:
def encontrar_maior_velociodade(iterable):
    # Ordena os elementos da lista pelo campo 'TipoDefinitivo'
    # Isso é necessário para que o groupby funcione corretamente
    iterable_sorted = sorted(iterable, key=lambda x: x['TipoDefinitivo'])

    # Agrupa os Pokémon por 'TipoDefinitivo'
    # groupby retorna pares (tipo, grupo_iterador)
    grouped_iterable = groupby(iterable_sorted, key=lambda x: x['TipoDefinitivo'])

    # Para cada grupo, aplica uma função que:
    # - pega o nome do tipo (x[0])
    # - encontra o Pokémon com maior velocidade dentro do grupo (usando max e a chave 'Speed')
    result = map(
        lambda x: (
            x[0],  # TipoDefinitivo
            max(x[1], key=lambda item: int(item['Speed']))  # Pokémon mais veloz do grupo
        ),
        grouped_iterable
    )

    # Retorna o resultado como uma lista de tuplas (TipoDefinitivo, Pokémon com maior velocidade)
    return list(result)


In [151]:
mostra_dados('pokemons_tratado.csv', encontrar_maior_velociodade)


('Bug-Bug', {'#': '617', 'Name': 'accelgor', 'Type 1': 'Bug', 'Type 2': 'Bug', 'Total': '495', 'HP': '80', 'Attack': '70', 'Defense': '40', 'Sp. Atk': '100', 'Sp. Def': '60', 'Speed': '145', 'Generation': '5', 'Legendary': 'False', 'TipoDefinitivo': 'Bug-Bug'})
('Bug-eElectric', {'#': '596', 'Name': 'galvantula', 'Type 1': 'Bug', 'Type 2': 'Electric', 'Total': '472', 'HP': '70', 'Attack': '77', 'Defense': '60', 'Sp. Atk': '97', 'Sp. Def': '60', 'Speed': '108', 'Generation': '5', 'Legendary': 'False', 'TipoDefinitivo': 'Bug-eElectric'})
('Bug-eFighting', {'#': '214', 'Name': 'heracross', 'Type 1': 'Bug', 'Type 2': 'Fighting', 'Total': '500', 'HP': '80', 'Attack': '125', 'Defense': '75', 'Sp. Atk': '40', 'Sp. Def': '95', 'Speed': '85', 'Generation': '2', 'Legendary': 'False', 'TipoDefinitivo': 'Bug-eFighting'})
('Bug-eFire', {'#': '637', 'Name': 'volcarona', 'Type 1': 'Bug', 'Type 2': 'Fire', 'Total': '550', 'HP': '85', 'Attack': '60', 'Defense': '65', 'Sp. Atk': '135', 'Sp. Def': '105',

## 4. Calcule a média de `HP` por geração para as gerações 1, 2 e 3.

### Exemplo de saída:
```python
('1', 65.81927710843374)
('2', 71.20754716981132)
('3', 66.54375)
```

In [152]:
def media_hp_geracao(iterable):
    # Filtra apenas os Pokémon das gerações 1, 2 e 3
    filtrados = filter(lambda x: x['Generation'] in ('1', '2', '3'), iterable)

    # Ordena os Pokémon por geração (necessário para o groupby funcionar corretamente)
    ordenados = sorted(filtrados, key=lambda x: int(x['Generation']))

    # Agrupa os Pokémon pela geração
    # Cada grupo será um par (geração, iterador com os pokémon dessa geração)
    agrupados = groupby(ordenados, key=lambda x: x['Generation'])

    # Função auxiliar para calcular a média de HP de cada grupo
    def calcula_media_u(grupo):
        gen, itens = grupo                   # Separando chave e valores
        lista_itens = list(itens)           # Convertendo iterador para lista para poder iterar múltiplas vezes
        soma_hp = sum(map(lambda item: int(item['HP']), lista_itens))  # Soma dos HPs convertidos para int
        qtd = len(lista_itens)              # Quantidade de pokémon no grupo
        return (gen, soma_hp / qtd)         # Retorna tupla com a geração e a média de HP

    # Aplica a função de média a cada grupo e retorna como lista
    return list(map(calcula_media_u, agrupados))


In [153]:
mostra_dados('pokemons_tratado.csv', media_hp_geracao)

('1', 65.81927710843374)
('2', 71.20754716981132)
('3', 66.54375)


# Parte 2: Listas encadeadas
Lembre-se, que todas as funções utilizadas devem seguir o paradigma funcional, ou seja, não devem utilizar laços de repetição e devem ser puras.

### Funções Auxiliares

In [135]:
def head(L):
    return L[0]

def tail(L):
    return L[1]

LL = (4, (12, (5, (-18, (-12, (16, (3, None)))))))

### Lista para testes:

## 5. Implemente uma função `primeLL` deve recebe uma lista encadeada `LL` de modo que produza uma nova lista `LL` somente com os números que são primos.

### Exemplo de saída:
```python
LL = (4, (12, (5, (-18, (-12, (16, (3, None)))))))
print(primeLL(LL))  # Saída: (5, (3, None))
```

In [155]:
import math

# Função recursiva para verificar se um número é primo
def is_prime(n, i=2):
    # Números menores que 2 não são primos
    if n < 2:
        return False
    # Se i ultrapassa a raiz de n, o número é primo
    if i > int(math.sqrt(n)):
        return True
    # Se n é divisível por i, não é primo
    if n % i == 0:
        return False
    # Chamada recursiva para o próximo divisor
    return is_prime(n, i + 1)


# Função recursiva que recebe uma lista encadeada (LL) e retorna uma nova lista apenas com os números primos
def prime_ll(LL):
    # Caso base: se a lista estiver vazia (None), retorna None
    if LL is None:
        return None

    # head(LL): pega o primeiro elemento da lista
    # tail(LL): pega o restante da lista
    header = head(LL)
    trailer = tail(LL)

    # Chamada recursiva no restante da lista
    filtrado = prime_ll(trailer)

    # Se o elemento atual (header) é primo, inclui na nova lista
    if is_prime(header):
        return (header, filtrado)
    else:
        # Caso contrário, ignora o elemento e retorna apenas o restante filtrado
        return filtrado

In [156]:
prime_ll(LL)

(5, (3, None))

## 6. Implemente uma função `fibonacciLL` que recebe um número `n` e retorne uma lista encadeada `LL` com os `n` primeiros números da sequência de Fibonacci.

### Exemplo de saída:
```python
print(fibonacciLL(10))  # Saída: (0, (1, (1, (2, (3, (5, (8, (13, (21, (34, None))))))))))
```

In [157]:
def fibonacciLL(n):
    # Função interna recursiva que constrói a lista encadeada de Fibonacci
    def build_fib_list(a, b, count):
        # Caso base: se já adicionamos n elementos, retornamos None (fim da lista)
        if count == 0:
            return None
        # Caso recursivo: cria um nó (a, resto da lista) com o próximo número de Fibonacci
        return (a, build_fib_list(b, a + b, count - 1))
    
    # Inicia a sequência de Fibonacci com 0 e 1, e começa a construção da lista
    return build_fib_list(0, 1, n)


In [158]:
print(fibonacciLL(10))

(0, (1, (1, (2, (3, (5, (8, (13, (21, (34, None))))))))))
